# background-overlay.yml

# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Background Overlay"
  description: "Component with a background image and a centered overlay image."
  icon: image
  tags: [image, overlay]

# Defines the structure of this component, as well as the default values
blueprint:
  bg_image:
    type: image
    label: "Background Image"
    description: "The image that will cover the entire viewport."
  overlay_image:
    type: image
    label: "Overlay Image"
    description: "The smaller image to overlay and center on the background image."
  overlay_alt:
    type: text
    label: "Overlay Image Alt Text"
    description: "Alt text for the overlay image."

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
